/**
 * FBLA Competitive Events Registry
 *
 * Source of truth for every competition tracked by FBLA One.
 * Based on the FBLA Competitive Events Guide. Re-verify each year - FBLA
 * adds/renames events for the new program of work.
 *
 * Events that require unique year-specific prompts (most "production",
 * "presentation", and case-study events) are listed but marked
 * `contentStatus: "coming-soon"`. Objective-test events have rich content
 * because the body of knowledge is stable year over year.
 */

export type CompetitionFormat =
  | "objective-test"
  | "objective-and-presentation"
  | "role-play"
  | "case-study"
  | "production"
  | "presentation"
  | "interview"
  | "team-test";

export const FORMAT_LABEL: Record<CompetitionFormat, string> = {
  "objective-test": "Objective Test",
  "objective-and-presentation": "Test + Presentation",
  "role-play": "Role Play",
  "case-study": "Case Study",
  production: "Production",
  presentation: "Presentation",
  interview: "Interview",
  "team-test": "Team Test",
};

export type CompetitionCategory =
  | "Accounting & Finance"
  | "Business Management"
  | "Career Development"
  | "Communication & Public Speaking"
  | "Information Technology"
  | "Marketing & Sales"
  | "Service & Leadership";

export const CATEGORIES: CompetitionCategory[] = [
  "Accounting & Finance",
  "Business Management",
  "Career Development",
  "Communication & Public Speaking",
  "Information Technology",
  "Marketing & Sales",
  "Service & Leadership",
];

export type StudyResource = {
  title: string;
  kind: "FBLA Guide" | "Article" | "Video" | "Course" | "Book" | "Practice" | "Reference";
  url: string;
  note?: string;
};

export type Competition = {
  slug: string;
  name: string;
  category: CompetitionCategory;
  format: CompetitionFormat;
  /** 1-2 sentence summary, shown on cards */
  description: string;
  /** Multi-paragraph detail, shown on detail page. Optional. */
  longDescription?: string;
  /** Format like "60 minutes, 100 questions" */
  duration?: string;
  /** Topics tested. Displayed as chips. */
  topics?: string[];
  /** Curated external study resources. */
  studyResources?: StudyResource[];
  /** Link to FBLA's official event description. */
  rubricUrl?: string;
  isTeam?: boolean;
  /** Drives whether the detail page shows full content or a coming-soon stub. */
  contentStatus: "complete" | "partial" | "coming-soon";
  /** Featured on the landing carousel + sorted first. */
  popular?: boolean;
};

const FBLA_EVENT_PAGE = "https://www.fbla.org/high-school/competitive-events/";

export const COMPETITIONS: Competition[] = [
  // ─── Accounting & Finance ────────────────────────────────────────────
  {
    slug: "accounting-i",
    name: "Accounting I",
    category: "Accounting & Finance",
    format: "objective-test",
    description: "Foundational accounting concepts: the accounting equation, journals, ledgers, financial statements, and adjusting entries.",
    longDescription:
      "Accounting I tests your understanding of the basic accounting cycle for sole proprietorships and partnerships. Expect questions on debits/credits, posting to the general ledger, preparing trial balances, adjusting and closing entries, and reading the four primary financial statements. This is the entry-level accounting event - Accounting II covers corporations, manufacturing, and managerial accounting.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "Accounting equation",
      "Debits & credits",
      "Journals & ledgers",
      "Trial balance",
      "Adjusting entries",
      "Closing entries",
      "Income statement",
      "Balance sheet",
      "Statement of cash flows",
      "Payroll basics",
      "Inventory methods (FIFO/LIFO)",
      "Depreciation",
    ],
    studyResources: [
      { title: "FBLA Accounting I Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "AccountingCoach - Accounting Basics", kind: "Course", url: "https://www.accountingcoach.com/accounting-basics/explanation" },
      { title: "AccountingCoach (free) - Bookkeeping Basics", kind: "Course", url: "https://www.accountingcoach.com/bookkeeping/explanation" },
      { title: "Investopedia - Accounting Cycle", kind: "Article", url: "https://www.investopedia.com/terms/a/accounting-cycle.asp" },
      { title: "Quizlet - FBLA Accounting I Practice Sets", kind: "Practice", url: "https://quizlet.com/subject/fbla-accounting-i/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
    popular: true,
  },
  {
    slug: "accounting-ii",
    name: "Accounting II",
    category: "Accounting & Finance",
    format: "objective-test",
    description: "Advanced accounting: corporate accounting, manufacturing, departmental accounting, and managerial decision-making.",
    longDescription:
      "Accounting II picks up where Accounting I ends. The test focuses on corporate equity (stocks, dividends, retained earnings), manufacturing and cost accounting (process vs. job-order), departmental accounting, partnerships, and managerial topics like budgeting and CVP analysis. Strong score requires deep familiarity with Accounting I plus comfort with cost allocations and contribution-margin math.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "Corporate equity",
      "Bonds payable",
      "Manufacturing accounting",
      "Job-order vs. process costing",
      "Cost-volume-profit analysis",
      "Budgeting & variance",
      "Departmental accounting",
      "Partnership accounting",
      "Statement of cash flows (indirect/direct)",
      "Ratio analysis",
    ],
    studyResources: [
      { title: "FBLA Accounting II Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "AccountingCoach - Managerial Accounting", kind: "Course", url: "https://www.accountingcoach.com/managerial-accounting/explanation" },
      { title: "Investopedia - Cost-Volume-Profit Analysis", kind: "Article", url: "https://www.investopedia.com/terms/c/cost-volume-profit-analysis.asp" },
      { title: "Khan Academy - Stocks & Bonds", kind: "Course", url: "https://www.khanacademy.org/economics-finance-domain/core-finance/stock-and-bonds" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
    popular: true,
  },
  {
    slug: "personal-finance",
    name: "Personal Finance",
    category: "Accounting & Finance",
    format: "objective-test",
    description: "Budgeting, credit, investing, insurance, taxes, and major life-stage financial planning.",
    longDescription:
      "Personal Finance tests practical money management for individuals: building a budget, managing credit and debt, investing (stocks, bonds, mutual funds, retirement accounts), insurance types (auto, health, life, property), and federal taxation basics. Heavy emphasis on real-world decision making - what's the better loan, which account to use for which goal, how compound interest works over decades.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "Budgeting & saving",
      "Credit scores & reports",
      "Loans & interest types",
      "Stocks & bonds basics",
      "Mutual funds & ETFs",
      "Retirement (401k, IRA, Roth)",
      "Insurance types",
      "Federal income tax",
      "Banking products",
      "Estate planning basics",
    ],
    studyResources: [
      { title: "FBLA Personal Finance Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "NGPF - Next Gen Personal Finance Curriculum", kind: "Course", url: "https://www.ngpf.org/curriculum/" },
      { title: "Khan Academy - Personal Finance", kind: "Course", url: "https://www.khanacademy.org/college-careers-more/personal-finance" },
      { title: "Investopedia - Personal Finance", kind: "Reference", url: "https://www.investopedia.com/personal-finance-4427760" },
      { title: "CFPB Money Smart for Young People", kind: "Course", url: "https://www.consumerfinance.gov/consumer-tools/educator-tools/youth-financial-education/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
    popular: true,
  },
  {
    slug: "financial-math",
    name: "Financial Math",
    category: "Accounting & Finance",
    format: "objective-test",
    description: "Time-value-of-money math: simple/compound interest, annuities, loans, and investment growth.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "Simple & compound interest",
      "Annuities (ordinary, due)",
      "Present value / future value",
      "Loan amortization",
      "Effective vs. nominal rates",
      "Discounted cash flow",
      "Investment growth math",
      "Sinking funds",
    ],
    studyResources: [
      { title: "FBLA Financial Math Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Khan Academy - Interest & Debt", kind: "Course", url: "https://www.khanacademy.org/economics-finance-domain/core-finance/interest-tutorial" },
      { title: "Investopedia - Time Value of Money", kind: "Article", url: "https://www.investopedia.com/terms/t/timevalueofmoney.asp" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "intro-to-financial-math",
    name: "Intro to Financial Math",
    category: "Accounting & Finance",
    format: "objective-test",
    description: "Foundational money math for 9th-10th graders: percent, interest, discounts, and basic business calculations.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Percentages", "Markup & discount", "Simple interest", "Payroll math", "Sales tax", "Tipping & gratuity"],
    studyResources: [
      { title: "FBLA Intro to Financial Math Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Khan Academy - Percents", kind: "Course", url: "https://www.khanacademy.org/math/pre-algebra/pre-algebra-ratios-rates/pre-algebra-percent" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "securities-investments",
    name: "Securities & Investments",
    category: "Accounting & Finance",
    format: "objective-test",
    description: "Equity and fixed-income markets, portfolio theory, valuation, and regulatory environment.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "Stocks (common, preferred)",
      "Bonds & yield",
      "Mutual funds & ETFs",
      "Options & derivatives basics",
      "Portfolio diversification",
      "Market indices",
      "SEC & FINRA regulation",
      "Order types (market, limit, stop)",
      "Valuation (P/E, dividend discount)",
    ],
    studyResources: [
      { title: "FBLA Securities & Investments Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Investopedia - Investing Basics", kind: "Reference", url: "https://www.investopedia.com/investing-4427685" },
      { title: "SEC.gov Investor.gov - Investing Basics", kind: "Reference", url: "https://www.investor.gov/introduction-investing" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "banking-financial-systems",
    name: "Banking & Financial Systems",
    category: "Accounting & Finance",
    format: "case-study",
    description: "Team case study: analyze a banking scenario and present recommendations.",
    longDescription:
      "Banking and Financial Systems is a team case study where competitors analyze a scenario involving a bank, credit union, or financial services firm and present findings and recommendations to judges. Teams typically have limited prep time before presenting. Strong teams apply core banking concepts -- capital adequacy, liquidity management, regulatory compliance -- to the specific scenario, quantify their recommendations with supporting data, and anticipate judge questions on risk and regulation.",
    topics: [
      "Federal Reserve and monetary policy",
      "Bank balance sheet (assets, liabilities, equity)",
      "Capital adequacy ratios (Tier 1, CAR)",
      "Liquidity risk and liquidity coverage ratio",
      "Credit analysis and loan underwriting",
      "FDIC insurance and bank failure mechanisms",
      "Basel III regulatory framework",
      "Interest rate risk management",
      "Retail vs. commercial banking products",
      "Case study presentation structure and Q&A technique",
    ],
    studyResources: [
      { title: "FBLA Banking & Financial Systems Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "FDIC Bank Resources", kind: "Reference", url: "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/" },
      { title: "Federal Reserve Education", kind: "Course", url: "https://www.federalreserveeducation.org/" },
      { title: "Investopedia Banking Basics", kind: "Reference", url: "https://www.investopedia.com/banking-4427754" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "insurance-risk-management",
    name: "Insurance & Risk Management",
    category: "Accounting & Finance",
    format: "objective-test",
    description: "Insurance product types, risk pooling, underwriting, and personal/commercial risk management.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Risk types", "Insurance principles", "Auto/home/life/health insurance", "Commercial insurance", "Underwriting", "Claims process"],
    studyResources: [
      { title: "FBLA Insurance & Risk Management Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Investopedia - Insurance Basics", kind: "Reference", url: "https://www.investopedia.com/insurance-4427716" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },

  // ─── Business Management ─────────────────────────────────────────────
  {
    slug: "business-management",
    name: "Business Management",
    category: "Business Management",
    format: "objective-test",
    description: "Management theory, organizational behavior, strategy, operations, and leadership.",
    longDescription:
      "Business Management tests classical and modern management theory: planning, organizing, leading, controlling. Topics span organizational structure, motivation theories (Maslow, Herzberg, McGregor), strategic management frameworks (SWOT, Porter), operations and supply chain, HR fundamentals, and quality management. Strong overlap with Intro to Business but goes deeper.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "Management functions (POLC)",
      "Organizational structures",
      "Motivation theories",
      "Leadership styles",
      "Strategic planning (SWOT, Porter)",
      "HR management basics",
      "Operations management",
      "Quality management (TQM, Six Sigma)",
      "Change management",
      "Business ethics",
    ],
    studyResources: [
      { title: "FBLA Business Management Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "OpenStax - Principles of Management", kind: "Book", url: "https://openstax.org/details/books/principles-management" },
      { title: "MindTools - Management Skills", kind: "Reference", url: "https://www.mindtools.com/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
    popular: true,
  },
  {
    slug: "business-law",
    name: "Business Law",
    category: "Business Management",
    format: "objective-test",
    description: "Contracts, torts, agency, business organizations, sales (UCC), employment law, and ethics.",
    longDescription:
      "Business Law focuses on the legal environment of US commerce. Heavy emphasis on contracts (formation, performance, breach, remedies), the UCC for sale of goods, business entities (sole proprietorship, partnership, LLC, corporation), agency relationships, employment law basics, and intellectual property. Tort law and constitutional/regulatory framework also appear.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "Contract law",
      "UCC sales",
      "Torts",
      "Business entities",
      "Agency",
      "Employment law",
      "Intellectual property",
      "Bankruptcy basics",
      "Consumer protection",
      "Constitutional law for business",
    ],
    studyResources: [
      { title: "FBLA Business Law Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Cornell LII - Wex Legal Encyclopedia", kind: "Reference", url: "https://www.law.cornell.edu/wex" },
      { title: "Investopedia - Business Law", kind: "Article", url: "https://www.investopedia.com/terms/b/business-law.asp" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "business-calculations",
    name: "Business Calculations",
    category: "Business Management",
    format: "objective-test",
    description: "Practical business math: percent, markups, payroll, statistics, and word problems.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Percent & markup", "Payroll & gross pay", "Discount calculations", "Statistics (mean, median, mode)", "Probability", "Word problems"],
    studyResources: [
      { title: "FBLA Business Calculations Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Khan Academy - Statistics & Probability", kind: "Course", url: "https://www.khanacademy.org/math/statistics-probability" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "business-communication",
    name: "Business Communication",
    category: "Communication & Public Speaking",
    format: "objective-test",
    description: "Grammar, mechanics, business writing, and professional communication conventions.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Grammar", "Punctuation & mechanics", "Business letter format", "Memos & emails", "Reports", "Active vs. passive voice", "Tone & register", "Editing"],
    studyResources: [
      { title: "FBLA Business Communication Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Purdue OWL - Business Writing", kind: "Reference", url: "https://owl.purdue.edu/owl/subject_specific_writing/professional_technical_writing/index.html" },
      { title: "Grammar Bytes!", kind: "Course", url: "https://chompchomp.com/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
    popular: true,
  },
  {
    slug: "economics",
    name: "Economics",
    category: "Business Management",
    format: "objective-test",
    description: "Micro and macro fundamentals: supply/demand, market structures, GDP, monetary and fiscal policy.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "Supply & demand",
      "Elasticity",
      "Market structures (perfect competition → monopoly)",
      "GDP & growth",
      "Inflation & unemployment",
      "Fiscal policy",
      "Monetary policy (Fed)",
      "International trade",
      "Externalities",
      "Economic indicators",
    ],
    studyResources: [
      { title: "FBLA Economics Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Khan Academy - Macroeconomics", kind: "Course", url: "https://www.khanacademy.org/economics-finance-domain/macroeconomics" },
      { title: "Khan Academy - Microeconomics", kind: "Course", url: "https://www.khanacademy.org/economics-finance-domain/microeconomics" },
      { title: "AP Economics CrashCourse (YouTube)", kind: "Video", url: "https://www.youtube.com/playlist?list=PLG3-zZqJtNVB6X-fdmHfDM2eRtmgrDC1u" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
    popular: true,
  },
  {
    slug: "marketing",
    name: "Marketing",
    category: "Marketing & Sales",
    format: "objective-test",
    description: "The 4 P's, segmentation, branding, advertising, digital marketing, and consumer behavior.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "Marketing mix (4 P's)",
      "Market segmentation",
      "Consumer behavior",
      "Branding",
      "Pricing strategies",
      "Promotion & advertising",
      "Digital & social media marketing",
      "Distribution channels",
      "Marketing research",
      "Product life cycle",
    ],
    studyResources: [
      { title: "FBLA Marketing Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "HubSpot Academy - Marketing", kind: "Course", url: "https://academy.hubspot.com/courses?topics=marketing" },
      { title: "Coursera - Intro to Marketing (Wharton)", kind: "Course", url: "https://www.coursera.org/learn/wharton-marketing" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
    popular: true,
  },
  {
    slug: "advertising",
    name: "Advertising",
    category: "Marketing & Sales",
    format: "objective-test",
    description: "Advertising history, media planning, copywriting, creative development, and digital advertising.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Advertising history", "Media planning & buying", "Creative process", "Copywriting", "Print, broadcast & digital ads", "Brand campaigns", "Ethics & regulation"],
    studyResources: [
      { title: "FBLA Advertising Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Google Skillshop - Ads Certifications", kind: "Course", url: "https://skillshop.withgoogle.com/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "sports-entertainment-management",
    name: "Sports & Entertainment Management",
    category: "Marketing & Sales",
    format: "objective-test",
    description: "Sports marketing, event management, sponsorships, ticketing, and the business of entertainment.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Sports marketing", "Event management", "Sponsorship sales", "Venue & ticketing", "Talent management", "Broadcasting rights"],
    studyResources: [
      { title: "FBLA Sports & Entertainment Management Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "SportsBusiness Journal - Articles", kind: "Reference", url: "https://www.sportsbusinessjournal.com/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "supply-chain-management",
    name: "Supply Chain Management",
    category: "Business Management",
    format: "objective-test",
    description: "Logistics, procurement, inventory, distribution, and global supply chain dynamics.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "Procurement & sourcing",
      "Inventory management (EOQ, JIT)",
      "Warehousing",
      "Transportation modes",
      "Distribution",
      "Reverse logistics",
      "Supply chain risk",
      "ERP systems",
    ],
    studyResources: [
      { title: "FBLA Supply Chain Management Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "ASCM (APICS) Resource Library", kind: "Reference", url: "https://www.ascm.org/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "health-care-administration",
    name: "Health Care Administration",
    category: "Business Management",
    format: "objective-test",
    description: "Healthcare systems, insurance, regulation, ethics, and the business of medicine in the US.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["US healthcare system", "Insurance (private, Medicare, Medicaid)", "HIPAA & patient privacy", "Hospital operations", "Healthcare regulation (ACA)", "Healthcare ethics"],
    studyResources: [
      { title: "FBLA Health Care Administration Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "KFF (Kaiser Family Foundation) - Health Policy", kind: "Reference", url: "https://www.kff.org/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "agribusiness",
    name: "Agribusiness",
    category: "Business Management",
    format: "objective-test",
    description: "Agriculture economics, farm management, agricultural finance, and global food systems.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Farm economics", "Ag finance & credit", "Commodity markets", "Sustainability", "Food supply chain", "Ag policy & subsidies"],
    studyResources: [
      { title: "FBLA Agribusiness Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "USDA Economic Research Service", kind: "Reference", url: "https://www.ers.usda.gov/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },

  // ─── Information Technology ──────────────────────────────────────────
  {
    slug: "computer-applications",
    name: "Computer Applications",
    category: "Information Technology",
    format: "objective-test",
    description: "Microsoft Office mastery: Word, Excel, PowerPoint, plus general productivity software.",
    longDescription:
      "Computer Applications tests practical productivity skills with a strong Microsoft Office bias. Excel questions go deep - formulas (VLOOKUP, IF, SUMIF, INDEX/MATCH), pivot tables, charting, conditional formatting. Word covers formatting, mail merge, styles, tables of contents. PowerPoint covers transitions, animations, slide masters. Plus general topics: file management, basic networking, accessibility.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "MS Word (formatting, mail merge, styles)",
      "MS Excel (formulas, pivot tables, charts)",
      "MS PowerPoint (transitions, masters)",
      "MS Outlook basics",
      "File management",
      "Cloud productivity",
      "Accessibility features",
    ],
    studyResources: [
      { title: "FBLA Computer Applications Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Microsoft Office Help & Training", kind: "Course", url: "https://support.microsoft.com/en-us/office" },
      { title: "GCFGlobal - Excel Tutorials", kind: "Course", url: "https://edu.gcfglobal.org/en/excel/" },
      { title: "ExcelJet - Functions & Formulas", kind: "Reference", url: "https://exceljet.net/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
    popular: true,
  },
  {
    slug: "computer-problem-solving",
    name: "Computer Problem Solving",
    category: "Information Technology",
    format: "objective-test",
    description: "Hardware troubleshooting, software diagnostics, networking issues, and IT support fundamentals.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Hardware components", "OS troubleshooting", "Networking basics", "Cybersecurity hygiene", "Help desk workflow", "Common Windows/macOS issues"],
    studyResources: [
      { title: "FBLA Computer Problem Solving Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "CompTIA A+ Study Materials", kind: "Course", url: "https://www.comptia.org/certifications/a" },
      { title: "Professor Messer - A+ Free Course", kind: "Video", url: "https://www.professormesser.com/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "cyber-security",
    name: "Cyber Security",
    category: "Information Technology",
    format: "objective-test",
    description: "Threats, defense, cryptography, network security, and security operations fundamentals.",
    longDescription:
      "Cyber Security covers the breadth of CompTIA Security+ level material. Expect questions on threat types (malware families, phishing, MITM, DDoS), cryptographic concepts (symmetric vs. asymmetric, hashing, PKI), network security (firewalls, IDS/IPS, VPNs), access control models, security operations (SOC, incident response), and policy/compliance basics. Many topics overlap with Networking Infrastructures.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "Threat types & vectors",
      "Cryptography",
      "Network security",
      "Authentication & access control",
      "Incident response",
      "Security policies & frameworks",
      "Endpoint security",
      "Cloud security basics",
      "Social engineering",
      "Compliance (PCI, HIPAA, GDPR)",
    ],
    studyResources: [
      { title: "FBLA Cyber Security Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Professor Messer - Security+ Free Course", kind: "Video", url: "https://www.professormesser.com/security-plus/sy0-701/sy0-701-video/sy0-701-comptia-security-plus-course/" },
      { title: "CISA - Cybersecurity Best Practices", kind: "Reference", url: "https://www.cisa.gov/topics/cybersecurity-best-practices" },
      { title: "OWASP Top 10", kind: "Reference", url: "https://owasp.org/www-project-top-ten/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
    popular: true,
  },
  {
    slug: "networking-infrastructures",
    name: "Networking Infrastructures",
    category: "Information Technology",
    format: "objective-test",
    description: "OSI model, TCP/IP, routing, switching, wireless, and network security fundamentals.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["OSI & TCP/IP models", "IP addressing & subnetting", "Routing & switching", "Wireless standards", "Network topologies", "Cabling", "Common protocols (DNS, DHCP, HTTP)", "Network security basics"],
    studyResources: [
      { title: "FBLA Networking Infrastructures Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Professor Messer - Network+ Free Course", kind: "Video", url: "https://www.professormesser.com/network-plus/n10-008/n10-008-training-course/" },
      { title: "Cisco Networking Academy", kind: "Course", url: "https://www.netacad.com/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "intro-to-information-technology",
    name: "Intro to Information Technology",
    category: "Information Technology",
    format: "objective-test",
    description: "Foundational IT for 9th-10th graders: hardware, software, internet, productivity, and digital citizenship.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Hardware basics", "Software types", "Internet fundamentals", "Productivity software", "Digital citizenship", "Cyber hygiene"],
    studyResources: [
      { title: "FBLA Intro to IT Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Code.org - Computer Science Principles", kind: "Course", url: "https://code.org/educate/csp" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "management-information-systems",
    name: "Management Information Systems",
    category: "Information Technology",
    format: "objective-test",
    description: "Business technology systems: ERP, CRM, databases, analytics, and IT strategy.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Database concepts (SQL basics)", "ERP & CRM systems", "Business intelligence", "Data warehousing", "System development lifecycle", "IT governance"],
    studyResources: [
      { title: "FBLA MIS Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "MIT OpenCourseWare - Information Technology", kind: "Course", url: "https://ocw.mit.edu/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "coding-programming",
    name: "Coding & Programming",
    category: "Information Technology",
    format: "objective-test",
    description: "Programming concepts: variables, control flow, data structures, OOP, and algorithm basics.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Variables & types", "Control flow (if/loop)", "Functions", "Arrays & collections", "OOP fundamentals", "Recursion", "Big-O basics", "Debugging"],
    studyResources: [
      { title: "FBLA Coding & Programming Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Codecademy - Intro to Programming", kind: "Course", url: "https://www.codecademy.com/" },
      { title: "Khan Academy - Intro to Computer Programming", kind: "Course", url: "https://www.khanacademy.org/computing/computer-programming" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "word-processing",
    name: "Word Processing",
    category: "Information Technology",
    format: "objective-test",
    description: "Deep Microsoft Word: styles, mail merge, tables of contents, references, collaboration, macros.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Document formatting", "Styles & themes", "Mail merge", "Tables & lists", "TOC & cross-references", "Track changes", "Macros & forms", "Templates"],
    studyResources: [
      { title: "FBLA Word Processing Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Microsoft Word Help & Training", kind: "Course", url: "https://support.microsoft.com/en-us/word" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },

  // ─── Career Development / Intro events ────────────────────────────────
  {
    slug: "intro-to-fbla",
    name: "Intro to FBLA",
    category: "Career Development",
    format: "objective-test",
    description: "FBLA history, mission, programs, competitive events, and parliamentary basics. The gateway event for 9th-10th graders.",
    longDescription:
      "Intro to FBLA is THE event to start with. It tests your knowledge of the organization itself: founding history, current programs (March of Dimes partnership, NLC, etc.), competitive event categories, business etiquette, and parliamentary procedure basics. Reading the FBLA-PBL Chapter Management Handbook front to back gets you most of the way there.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: [
      "FBLA history (founded 1940)",
      "FBLA-PBL structure",
      "Mission & creed",
      "Competitive events overview",
      "March of Dimes partnership",
      "NLC, SLC, RLC events",
      "Business etiquette",
      "Parliamentary procedure basics",
    ],
    studyResources: [
      { title: "FBLA Intro to FBLA Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "FBLA Chapter Management Handbook", kind: "Reference", url: "https://www.fbla.org/" },
      { title: "FBLA-PBL Bylaws", kind: "Reference", url: "https://www.fbla.org/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
    popular: true,
  },
  {
    slug: "intro-to-business",
    name: "Intro to Business",
    category: "Business Management",
    format: "objective-test",
    description: "Business fundamentals for 9th-10th graders: economics basics, business types, marketing, management, and finance overview.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Economic systems", "Business types", "Marketing basics", "Management basics", "Personal finance basics", "Entrepreneurship"],
    studyResources: [
      { title: "FBLA Intro to Business Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Khan Academy - Entrepreneurship & Innovation", kind: "Course", url: "https://www.khanacademy.org/college-careers-more/career-content/intro-to-business" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
    popular: true,
  },
  {
    slug: "intro-to-business-communication",
    name: "Intro to Business Communication",
    category: "Communication & Public Speaking",
    format: "objective-test",
    description: "Communication fundamentals for 9th-10th graders: grammar, business writing, and professional email.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Grammar basics", "Punctuation", "Email etiquette", "Business letters", "Professionalism"],
    studyResources: [
      { title: "FBLA Intro to Business Communication Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Purdue OWL - General Writing", kind: "Reference", url: "https://owl.purdue.edu/owl/general_writing/index.html" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "intro-to-business-procedures",
    name: "Intro to Business Procedures",
    category: "Business Management",
    format: "objective-test",
    description: "Office procedures for 9th-10th graders: filing, records, mail, telephone, scheduling, and document handling.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["Filing systems", "Records management", "Mail handling", "Scheduling", "Phone procedures", "Office equipment"],
    studyResources: [{ title: "FBLA Intro to Business Procedures Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE }],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "political-science",
    name: "Political Science",
    category: "Career Development",
    format: "objective-test",
    description: "US government, political theory, comparative politics, and international relations.",
    duration: "60 minutes, 100 multiple-choice questions",
    topics: ["US Constitution", "Branches of government", "Civil liberties & rights", "Elections & parties", "Political theory", "International relations basics"],
    studyResources: [
      { title: "FBLA Political Science Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Khan Academy - AP US Government", kind: "Course", url: "https://www.khanacademy.org/humanities/ap-us-government-and-politics" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "future-business-leader",
    name: "Future Business Leader",
    category: "Career Development",
    format: "objective-and-presentation",
    description: "Test + interview/presentation. Tests business knowledge plus leadership communication.",
    longDescription:
      "Future Business Leader combines a 60-question objective test on general business knowledge with an interactive interview component where competitors present their leadership goals and answer judge questions. High scorers on both components advance. The test covers business fundamentals across accounting, management, marketing, and economics.",
    topics: [
      "Business fundamentals (all areas)",
      "Leadership theories",
      "Goal setting (SMART goals)",
      "Career planning",
      "Interview skills",
      "Business current events",
      "FBLA knowledge",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "MindTools - Leadership Skills", kind: "Reference", url: "https://www.mindtools.com/" },
      { title: "LinkedIn Learning - Business Fundamentals", kind: "Course", url: "https://www.linkedin.com/learning/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "future-business-educator",
    name: "Future Business Educator",
    category: "Career Development",
    format: "objective-and-presentation",
    description: "Test + interview/presentation on teaching business education as a career.",
    longDescription:
      "Future Business Educator is for members interested in teaching business education as a career. Competitors take an objective test on business education pedagogy and then present to judges about why they want to be a business teacher, their teaching philosophy, and their understanding of the profession. Knowledge of curriculum design and education technology is helpful.",
    topics: [
      "Business education pedagogy",
      "Curriculum development",
      "Classroom management",
      "Education technology (EdTech)",
      "Career and technical education (CTE)",
      "Professional development for educators",
      "Standards-based instruction",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "NBEA - National Business Education Association", kind: "Reference", url: "https://www.nbea.org/" },
      { title: "ACTE - Career Technical Education", kind: "Reference", url: "https://www.acteonline.org/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },

  // ─── Coming-soon stubs (prompt-based events) ──────────────────────────
  {
    slug: "broadcast-journalism",
    name: "Broadcast Journalism",
    category: "Communication & Public Speaking",
    format: "production",
    description: "Produce a broadcast journalism piece. Requires year-specific prompt.",
    longDescription:
      "Broadcast Journalism teams produce a 3-5 minute broadcast journalism segment on a topic released annually. Strong entries look like professional local news: clear anchor delivery, concise scripting in inverted pyramid format, relevant supporting visuals, sound bites from interviews, and tight editing. The topic changes each year, but the craft and format expectations are constant -- master the production fundamentals and you can execute on any topic.",
    topics: [
      "Inverted pyramid news structure",
      "Split-page TV script format",
      "On-camera delivery and presence",
      "Interview technique and question writing",
      "B-roll planning and visual storytelling",
      "Three-point lighting setup",
      "Audio capture (boom pole, lavalier mic, room tone)",
      "Non-linear video editing (Premiere Pro, DaVinci Resolve)",
      "Broadcast journalism ethics and accuracy standards",
      "Color correction, audio mixing, and final export",
    ],
    studyResources: [
      { title: "FBLA Broadcast Journalism Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "SPJ Code of Ethics", kind: "Reference", url: "https://www.spj.org/ethicscode.asp" },
      { title: "Poynter - Journalism Resources", kind: "Reference", url: "https://www.poynter.org/" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "business-ethics",
    name: "Business Ethics",
    category: "Service & Leadership",
    format: "presentation",
    description: "Team presentation analyzing a business ethics scenario. Year-specific topic.",
    longDescription:
      "Business Ethics teams receive an annual scenario involving an ethical dilemma -- whistleblowing, data privacy, executive misconduct, environmental harm, or conflicts of interest -- and present analysis and recommendations to judges. Top teams do not just state a conclusion: they apply multiple ethical frameworks, identify every stakeholder, acknowledge competing interests, and propose specific, actionable solutions. Judges evaluate depth of analysis over the final verdict.",
    topics: [
      "Utilitarian ethics (greatest good for the greatest number)",
      "Deontological ethics (duty-based, Kantian framework)",
      "Virtue ethics and character-based reasoning",
      "Stakeholder theory and stakeholder mapping",
      "Corporate social responsibility (CSR) and ESG",
      "Whistleblowing law and ethical duty to report",
      "Conflicts of interest and disclosure requirements",
      "Data privacy principles and GDPR basics",
      "Ethical decision-making models (Potter Box, PLUS model)",
      "Presenting ethical analysis to skeptical audiences",
    ],
    studyResources: [
      { title: "FBLA Business Ethics Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Institute for Business Ethics", kind: "Reference", url: "https://www.iebe.org/" },
      { title: "Markkula Center - Ethical Decision Making", kind: "Reference", url: "https://www.scu.edu/ethics/ethics-resources/ethical-decision-making/" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "business-financial-plan",
    name: "Business Financial Plan",
    category: "Accounting & Finance",
    format: "presentation",
    description: "Develop and present a financial plan for a business scenario. Year-specific topic.",
    longDescription:
      "Business Financial Plan teams develop and present a comprehensive financial plan for a business scenario released each year. Judges are typically real finance professionals who expect realistic assumptions, correct financial mechanics, and the ability to defend every number. The plan must cover pro forma financials, break-even analysis, funding sources, and key ratios. The scenarios change annually, but the financial modeling skills required are constant.",
    topics: [
      "Pro forma income statement (3-year projection)",
      "Pro forma balance sheet construction",
      "Cash flow statement (direct and indirect methods)",
      "Break-even analysis (fixed costs, variable costs, contribution margin)",
      "Startup and operating cost estimation",
      "Funding sources (bootstrapping, debt financing, equity, grants)",
      "Financial ratios (current ratio, debt-to-equity, ROE, gross margin)",
      "Sensitivity analysis and best/base/worst case scenarios",
      "Valuation basics (revenue multiples, DCF overview)",
      "Presenting financial models to finance-literate judges",
    ],
    studyResources: [
      { title: "FBLA Business Financial Plan Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "SBA - Business Plan Guide", kind: "Reference", url: "https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan" },
      { title: "Investopedia - Financial Plan", kind: "Article", url: "https://www.investopedia.com/terms/f/financial-plan.asp" },
      { title: "SCORE Financial Templates", kind: "Reference", url: "https://score.org/resource/business-plan-template-startup-business" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "business-plan",
    name: "Business Plan",
    category: "Marketing & Sales",
    format: "presentation",
    description: "Build and present a full business plan. Year-specific topic.",
    longDescription:
      "Business Plan is FBLA's flagship team event and one of its most prestigious. Competitors build a full business plan for a concept of their own choosing -- not a year-specific prompt -- and present to panels of real business professionals. The plan must cover every dimension: executive summary, company overview, market analysis, competitive analysis, marketing strategy, operations plan, management team, and 3-year financial projections. NLC-winning teams have both a rigorous plan and a compelling, confident pitch delivery.",
    duration: "Presentation: 20 minutes + 5 min Q&A; written plan submitted in advance",
    topics: [
      "Executive summary writing (hook, problem, solution, ask)",
      "Market research and sizing (TAM, SAM, SOM)",
      "Primary and secondary research methods",
      "Competitive landscape analysis and differentiation",
      "Marketing strategy (4Ps, customer acquisition, digital channels)",
      "Operations plan (location, processes, technology, supply chain)",
      "Organizational structure and founding team bios",
      "3-year financial projections (P&L, balance sheet, cash flow)",
      "Funding ask, use of funds, and investor returns",
      "Pitch delivery, rehearsal technique, and Q&A preparation",
    ],
    studyResources: [
      { title: "FBLA Business Plan Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "SBA.gov - Business Plan Guide", kind: "Reference", url: "https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan" },
      { title: "SCORE - Business Plan Template", kind: "Reference", url: "https://score.org/resource/business-plan-template-startup-business" },
      { title: "HBR - How to Write a Winning Business Plan", kind: "Article", url: "https://hbr.org/2017/05/how-to-write-a-winning-business-plan" },
    ],
    isTeam: true,
    popular: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "community-service-project",
    name: "Community Service Project",
    category: "Service & Leadership",
    format: "presentation",
    description: "Present a chapter community service project. Chapter-specific.",
    longDescription:
      "Community Service Project teams document and present their chapter's community service work from the current year. Both a written report and a live presentation are required. The strongest entries treat it like a nonprofit impact report: they identify a specific community need, describe coordinated chapter action, measure outcomes with real data, and articulate what was learned. Judges reward chapters that went beyond one-day events to run sustained, well-organized projects.",
    topics: [
      "Community needs assessment and problem framing",
      "Project planning (SMART goals, timeline, roles, budget)",
      "Volunteer recruitment, training, and coordination",
      "Partnership development with organizations and sponsors",
      "Measuring and documenting community impact",
      "Photography and documentation best practices",
      "Grant writing structure (purpose, activities, outcomes, evaluation)",
      "Presenting results, challenges, and lessons learned",
      "Sustainability plan for continuing the project",
      "Chapter leadership and member engagement development",
    ],
    studyResources: [
      { title: "FBLA Community Service Project Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Points of Light - Volunteer Resources", kind: "Reference", url: "https://www.pointsoflight.org/programs/" },
      { title: "Council of Nonprofits Resources", kind: "Reference", url: "https://www.councilofnonprofits.org/" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "data-analysis",
    name: "Data Analysis",
    category: "Information Technology",
    format: "production",
    description: "Analyze a dataset and produce a written report. Year-specific dataset.",
    longDescription:
      "Data Analysis challenges competitors to work with a real-world dataset and produce a written analytical report. The dataset and prompt are released each year. Strong performers excel at data cleaning, statistical analysis, visualization, and drawing actionable business conclusions. Excel is the minimum requirement; Python (pandas/matplotlib) or R can elevate the analysis.",
    duration: "3 hours on-site to analyze the dataset and write the report",
    topics: [
      "Descriptive statistics (mean, median, mode, standard deviation)",
      "Data cleaning and validation",
      "Excel pivot tables and formulas",
      "Chart selection and visualization",
      "Trend and correlation analysis",
      "Regression basics",
      "Report writing and recommendations",
      "Data storytelling",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Kaggle - Free Data Analysis Courses", kind: "Course", url: "https://www.kaggle.com/learn" },
      { title: "Towards Data Science - Articles", kind: "Reference", url: "https://towardsdatascience.com/" },
      { title: "ExcelJet - Excel Functions Reference", kind: "Reference", url: "https://exceljet.net/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "digital-animation",
    name: "Digital Animation",
    category: "Information Technology",
    format: "production",
    description: "Produce a short digital animation. Year-specific prompt.",
    longDescription:
      "Digital Animation teams produce a short animated video (typically 2-4 minutes) on a topic announced annually. Teams are judged on animation quality, storytelling, character design, audio, and adherence to the prompt. The topic changes each year, but the craft expectations are constant: solid storyboarding, clean animation principles, thoughtful sound design, and professional export. Adobe Animate, Blender, After Effects, and Toon Boom Harmony are all commonly used.",
    topics: [
      "12 principles of animation (squash and stretch, anticipation, staging, follow-through, etc.)",
      "Storyboarding and animatic creation",
      "Character design and model sheets",
      "Rigging and keyframe vs. motion-path animation",
      "Adobe Animate or Blender workflow",
      "Motion graphics and kinetic typography",
      "Sound design, music selection, and licensing rules",
      "Color theory and background art composition",
      "Export formats, frame rate, and file delivery standards",
      "Team asset management and version control",
    ],
    studyResources: [
      { title: "FBLA Digital Animation Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "The 12 Principles of Animation", kind: "Reference", url: "https://www.animationmentor.com/blog/the-12-principles-of-animation/" },
      { title: "Blender Guru - Free Blender Tutorials", kind: "Video", url: "https://www.youtube.com/c/BlenderGuru" },
      { title: "Adobe Animate Tutorials", kind: "Course", url: "https://helpx.adobe.com/animate/tutorials.html" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "digital-video-production",
    name: "Digital Video Production",
    category: "Communication & Public Speaking",
    format: "production",
    description: "Produce a short video. Year-specific prompt.",
    longDescription:
      "Digital Video Production teams plan, film, and edit a 3-5 minute video on a topic released annually -- a PSA, documentary, commercial, or narrative. Judges evaluate concept, cinematography, audio, editing, storytelling, and prompt adherence. Top teams invest heavily in pre-production (script, shot list, storyboard) before a single frame is shot. Post-production polish -- color grade, sound mix, titles -- is what separates strong entries from winning ones.",
    topics: [
      "Pre-production: script writing, storyboard, and shot list",
      "Camera operation: framing, composition (rule of thirds, headroom, lead room)",
      "Lighting fundamentals (3-point, natural light, reflectors)",
      "Sound recording (lavalier mic, boom pole, room tone management)",
      "Editing workflow in Premiere Pro or DaVinci Resolve",
      "Color correction and color grading (exposure, contrast, LUTs)",
      "Audio mixing and dialogue clarity",
      "Text overlay and title card design",
      "Exporting for delivery (codec, resolution, frame rate, file size)",
      "Production roles: director, director of photography, audio lead, editor",
    ],
    studyResources: [
      { title: "FBLA Digital Video Production Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Film Riot - Video Production Tutorials", kind: "Video", url: "https://www.youtube.com/c/FilmRiot" },
      { title: "DaVinci Resolve - Free Training", kind: "Course", url: "https://www.blackmagicdesign.com/products/davinciresolve/training" },
      { title: "YouTube Creator Academy", kind: "Course", url: "https://creatoracademy.youtube.com/" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "entrepreneurship",
    name: "Entrepreneurship",
    category: "Business Management",
    format: "case-study",
    description: "Team case study analyzing an entrepreneurship scenario.",
    longDescription:
      "Entrepreneurship is a team case study where competitors receive a business scenario on-site and have limited prep time to develop and present a solution. Judges look for innovative thinking, financial viability, market awareness, and a clear go-to-market plan. Top teams divide analysis roles quickly and structure their presentation around a problem, solution, market, and financial framework.",
    duration: "60 minutes preparation + 10-15 minutes presentation + Q&A",
    topics: [
      "Lean startup methodology",
      "Customer discovery and validation",
      "Value proposition canvas",
      "Business model canvas",
      "Minimum viable product (MVP)",
      "Market sizing (TAM, SAM, SOM)",
      "Startup financial modeling",
      "Pitching under time pressure",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Y Combinator - Startup School (free)", kind: "Course", url: "https://www.startupschool.org/" },
      { title: "SCORE - Startup Resources", kind: "Reference", url: "https://score.org/resource/business-plan-template-startup-business" },
      { title: "Investopedia - Lean Startup", kind: "Article", url: "https://www.investopedia.com/terms/l/lean-startup.asp" },
    ],
    isTeam: true,
    popular: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "graphic-design",
    name: "Graphic Design",
    category: "Marketing & Sales",
    format: "production",
    description: "Produce a graphic design piece. Year-specific brief.",
    longDescription:
      "Graphic Design competitors create a piece (poster, logo, advertisement, or infographic) based on an annually released brief. Judges score on design principles, technical execution, creativity, and adherence to the brief. Adobe Illustrator and Photoshop are the industry-standard tools. Entries that demonstrate strong grasp of contrast, hierarchy, and white space consistently score highest.",
    topics: [
      "Design principles (contrast, alignment, repetition, proximity)",
      "Color theory and palettes",
      "Typography and type pairing",
      "Grid systems and layout",
      "Logo design principles",
      "Adobe Illustrator basics",
      "Adobe Photoshop basics",
      "File prep for print vs. screen",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Adobe Graphic Design Learning", kind: "Course", url: "https://www.adobe.com/learn/graphic-design.html" },
      { title: "Canva Design School", kind: "Course", url: "https://www.canva.com/learn/design/" },
      { title: "Awwwards - Design Inspiration", kind: "Reference", url: "https://www.awwwards.com/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "hospitality-event-management",
    name: "Hospitality & Event Management",
    category: "Business Management",
    format: "case-study",
    description: "Team case study on a hospitality scenario.",
    longDescription:
      "Hospitality and Event Management is a team case study where competitors receive a scenario -- planning a corporate conference, fundraising gala, product launch, or similar event -- and present a full event plan to judges, who are often hospitality industry professionals. Strong plans address every operational dimension: venue selection, catering, marketing, attendee experience, budget with contingencies, and risk mitigation. The scenario changes each year; the operational excellence expected does not.",
    topics: [
      "Event planning lifecycle (scoping, contracting, logistics, execution, post-event)",
      "Venue selection criteria, site visits, and contract terms",
      "Food and beverage management (menus, dietary restrictions, service styles, alcohol licensing)",
      "Event marketing, registration platforms, and attendee communication",
      "Budget construction, cost control, and contingency reserves",
      "Day-of logistics, run-of-show timeline, and staffing",
      "Guest experience design and service recovery protocols",
      "Risk management: weather, no-shows, A/V failure, medical emergencies",
      "Post-event evaluation, attendee feedback, and ROI measurement",
      "Hospitality technology: event apps, check-in systems, A/V platforms",
    ],
    studyResources: [
      { title: "FBLA Hospitality & Event Management Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "PCMA - Events Industry Resources", kind: "Reference", url: "https://www.pcma.org/resources/" },
      { title: "MPI - Meeting Professionals International", kind: "Course", url: "https://www.mpi.org/education" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "impromptu-speaking",
    name: "Impromptu Speaking",
    category: "Communication & Public Speaking",
    format: "presentation",
    description: "Live impromptu speaking on a randomly assigned topic.",
    longDescription:
      "Impromptu Speaking gives competitors 5 minutes to prepare and deliver a 1-4 minute speech on a randomly assigned topic (a quote, a question, or a current-events scenario). Judges score on organization, content quality, delivery, and time management. The PREP framework (Point, Reason, Example, Point) is the most reliable structure for immediate use under pressure.",
    topics: [
      "PREP framework (Point, Reason, Example, Point)",
      "PEEL structure alternative",
      "Opening hooks (question, statistic, story)",
      "Signposting and transitions",
      "Closing techniques",
      "Eye contact and audience engagement",
      "Vocal variety (pace, pitch, pause)",
      "Eliminating filler words",
      "Staying calm under time pressure",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Toastmasters - Public Speaking Tips", kind: "Reference", url: "https://www.toastmasters.org/resources/public-speaking-tips" },
      { title: "TED - How to Give a Great Talk", kind: "Video", url: "https://www.ted.com/playlists/574/how_to_make_a_great_presentati" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "introduction-to-public-speaking",
    name: "Intro to Public Speaking",
    category: "Communication & Public Speaking",
    format: "presentation",
    description: "Prepared speech for 9th-10th graders. Year-specific topic.",
    longDescription:
      "Intro to Public Speaking is the 9th-10th grade version of the Public Speaking event. Competitors deliver a prepared 3-5 minute speech on an annually assigned topic. Judging focuses on content quality, structure, delivery fundamentals, and audience engagement. This is the ideal entry point for competitive public speaking in FBLA - building habits early pays off at State and NLC.",
    topics: [
      "Speech structure (intro, body, conclusion)",
      "Transitions between points",
      "Eye contact techniques",
      "Vocal projection and pacing",
      "Physical presence and gestures",
      "Using note cards vs. full memorization",
      "Practice techniques (record yourself, practice in front of mirror)",
      "Opening with impact",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Toastmasters - Public Speaking Tips", kind: "Reference", url: "https://www.toastmasters.org/resources/public-speaking-tips" },
      { title: "TED Talks - Great Presentation Examples", kind: "Video", url: "https://www.ted.com/playlists/574/how_to_make_a_great_presentati" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "job-interview",
    name: "Job Interview",
    category: "Career Development",
    format: "interview",
    description: "Submit a resume and cover letter and interview for a mock position.",
    longDescription:
      "Job Interview contestants submit a one-page resume and cover letter for a mock position announced each year, then complete a 10-minute professional interview with judges. Scoring covers resume quality, cover letter quality, professional appearance, verbal communication, non-verbal cues, and quality of responses. The STAR method (Situation, Task, Action, Result) is essential for behavioral questions.",
    topics: [
      "Resume writing (one page, bullet format, quantified achievements)",
      "Cover letter format and content",
      "STAR method for behavioral questions",
      "Common interview questions and strong answers",
      "Researching the role and company",
      "Professional attire standards",
      "Handshake, posture, and eye contact",
      "Asking good questions at the end",
      "Follow-up thank-you note",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "LinkedIn - Resume Tips", kind: "Reference", url: "https://www.linkedin.com/business/talent/blog/talent-acquisition/tips-for-writing-a-great-linkedin-profile" },
      { title: "Glassdoor - Common Interview Questions", kind: "Reference", url: "https://www.glassdoor.com/blog/common-interview-questions/" },
      { title: "The Muse - Interview Prep Guide", kind: "Reference", url: "https://www.themuse.com/advice/interview-questions-and-answers" },
    ],
    popular: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "mobile-application-development",
    name: "Mobile Application Development",
    category: "Information Technology",
    format: "production",
    description: "Build a mobile app. Year-specific prompt.",
    longDescription:
      "Mobile Application Development teams design, build, and document a mobile app based on an annually released brief. Judging covers technical implementation, UI/UX design quality, feature completeness, documentation quality, and live demonstration. Native (Swift for iOS, Kotlin for Android) and cross-platform (Flutter, React Native) approaches are both accepted.",
    topics: [
      "UI/UX design principles for mobile",
      "Navigation patterns (tabs, drawers, stacks)",
      "API integration and async data",
      "Local storage and state management",
      "User authentication flow",
      "App store submission guidelines",
      "Flutter or React Native fundamentals",
      "Testing on device vs. simulator",
      "Technical documentation",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Apple Human Interface Guidelines", kind: "Reference", url: "https://developer.apple.com/design/human-interface-guidelines/" },
      { title: "Material Design Guidelines (Google)", kind: "Reference", url: "https://material.io/design" },
      { title: "Flutter Official Documentation", kind: "Course", url: "https://docs.flutter.dev/" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "parliamentary-procedure",
    name: "Parliamentary Procedure",
    category: "Service & Leadership",
    format: "team-test",
    description: "Team event on Robert's Rules. Test + live demo.",
    longDescription:
      "Parliamentary Procedure tests a team's mastery of Robert's Rules of Order. The event has two parts: a written objective test covering motions, voting requirements, and procedural rules; and a live demonstration where teams conduct a mock meeting, handling motions, amendments, and points of order in real time. The chair role is the hardest - practice announcing each motion class by name.",
    duration: "Test: 30 questions; Demonstration: 10-minute live mock meeting",
    topics: [
      "Main motions",
      "Subsidiary motions (amend, postpone, table, previous question, refer)",
      "Privileged motions (adjourn, recess, point of privilege)",
      "Incidental motions (point of order, appeal, suspend rules)",
      "Voting thresholds (majority vs. two-thirds)",
      "Quorum requirements",
      "Agenda order",
      "Amending motions",
      "Officer roles (president, secretary, parliamentarian)",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Robert's Rules of Order (official)", kind: "Reference", url: "https://www.robertsrules.com/" },
      { title: "Toastmasters - Parliamentary Procedure", kind: "Reference", url: "https://www.toastmasters.org/resources/parliamentary-procedure" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "public-service-announcement",
    name: "Public Service Announcement",
    category: "Communication & Public Speaking",
    format: "production",
    description: "Produce a PSA video. Year-specific topic.",
    longDescription:
      "PSA teams produce a 30-60 second public service announcement video on a social issue released annually. Judging covers message clarity, emotional impact, production quality, factual accuracy, and call-to-action effectiveness. The most effective PSAs -- study the Ad Council portfolio -- use one unexpected angle, one concrete human story, and one clear ask. The issue changes each year; the persuasive short-form video craft is constant.",
    topics: [
      "PSA format conventions (15, 30, and 60-second structures)",
      "Target audience identification and message tailoring",
      "Emotional appeal techniques (fear appeals, hope, empathy, social proof)",
      "Credibility and factual accuracy in advocacy messaging",
      "Single clear call-to-action construction",
      "Storytelling structure compressed to under 60 seconds",
      "Visual metaphor, symbolism, and imagery selection",
      "Script writing for broadcast pacing and natural delivery",
      "Music selection, licensing, and emotional tone",
      "Ad Council PSA archive analysis and competitive benchmarking",
    ],
    studyResources: [
      { title: "FBLA Public Service Announcement Event Page", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Ad Council - PSA Examples", kind: "Reference", url: "https://www.adcouncil.org/campaigns" },
      { title: "Adobe Premiere Pro Tutorials", kind: "Course", url: "https://helpx.adobe.com/premiere-pro/tutorials.html" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "public-speaking",
    name: "Public Speaking",
    category: "Communication & Public Speaking",
    format: "presentation",
    description: "Prepared speech. Year-specific topic.",
    longDescription:
      "Public Speaking competitors deliver a 4-6 minute prepared speech on an annually assigned topic. Judging covers content quality, research depth, organization, and delivery. A memorable opening hook, strong use of evidence (statistics, stories, expert quotes), clear transitions, and a compelling call-to-action conclusion separate high scorers from the rest.",
    topics: [
      "Speech structure (3-5 main points)",
      "Researching and citing evidence",
      "Opening hooks (story, shocking statistic, rhetorical question)",
      "Transitions and signposting",
      "Persuasive techniques (ethos, pathos, logos)",
      "Eye contact and audience connection",
      "Vocal variety (rate, pitch, volume, pause)",
      "Gestures and movement",
      "Closing with impact and call to action",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Toastmasters - Public Speaking Tips", kind: "Reference", url: "https://www.toastmasters.org/resources/public-speaking-tips" },
      { title: "TED Talks - Presentation Techniques", kind: "Video", url: "https://www.ted.com/playlists/574/how_to_make_a_great_presentati" },
      { title: "Coursera - Dynamic Public Speaking", kind: "Course", url: "https://www.coursera.org/learn/public-speaking" },
    ],
    popular: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "publication-design",
    name: "Publication Design",
    category: "Marketing & Sales",
    format: "production",
    description: "Design a publication. Year-specific brief.",
    longDescription:
      "Publication Design competitors create a multi-page publication (newsletter, magazine layout, brochure, or similar) based on an annually released brief. Judging covers layout quality, typography choices, use of images and white space, visual consistency, and adherence to the brief. Adobe InDesign is the professional-standard tool; strong entries have a clear visual hierarchy and consistent grid.",
    topics: [
      "Page layout and grid systems",
      "Typography pairing and hierarchy",
      "Color palette and brand consistency",
      "Image placement and white space",
      "Adobe InDesign basics (master pages, styles, grids)",
      "Cover design principles",
      "Export for print vs. digital PDF",
      "Style guide application",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "Adobe InDesign Tutorials", kind: "Course", url: "https://helpx.adobe.com/indesign/tutorials.html" },
      { title: "Smashing Magazine - Typography", kind: "Reference", url: "https://www.smashingmagazine.com/category/typography/" },
    ],
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "social-media-strategies",
    name: "Social Media Strategies",
    category: "Marketing & Sales",
    format: "presentation",
    description: "Team presentation of a social media campaign. Year-specific scenario.",
    longDescription:
      "Social Media Strategies teams develop and present a comprehensive social media campaign for a brand or scenario released annually. Judges look for platform-specific strategy, realistic content calendar, smart KPI selection, audience targeting, and budget allocation. Teams that show mockups of actual posts and a clear measurement framework score highest.",
    duration: "Presentation: 20 minutes + 5 min Q&A",
    topics: [
      "Platform algorithms (Instagram, TikTok, LinkedIn, X)",
      "Content calendar development",
      "KPIs (reach, engagement rate, conversion, ROI)",
      "Influencer marketing strategy",
      "Paid vs. organic strategy",
      "A/B testing for content",
      "Brand voice and content guidelines",
      "Analytics tools (Meta Insights, Google Analytics)",
      "Community management",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "HubSpot - Social Media Marketing Certification", kind: "Course", url: "https://academy.hubspot.com/courses/social-media-marketing" },
      { title: "Meta Blueprint - Free Social Media Courses", kind: "Course", url: "https://www.facebook.com/business/learn" },
      { title: "Google Digital Garage", kind: "Course", url: "https://learndigital.withgoogle.com/" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
  {
    slug: "website-coding-development",
    name: "Website Coding & Development",
    category: "Information Technology",
    format: "production",
    description: "Build a website. Year-specific brief.",
    longDescription:
      "Website Coding and Development teams build and document a fully functional website based on an annually released brief. Judging covers technical implementation, UX/UI design quality, mobile responsiveness, web accessibility, code quality, and live demonstration. Teams using modern frameworks (React, Next.js, Vue) with clean CSS score well on technical criteria; accessibility and performance metrics matter too.",
    topics: [
      "HTML5 semantic structure",
      "CSS layouts (Flexbox, Grid)",
      "JavaScript and TypeScript fundamentals",
      "React or Vue.js framework",
      "Responsive design and mobile-first approach",
      "Web accessibility (WCAG 2.1 guidelines)",
      "Performance optimization (Core Web Vitals)",
      "Git version control",
      "API integration",
      "Technical documentation",
    ],
    studyResources: [
      { title: "FBLA Guide", kind: "FBLA Guide", url: FBLA_EVENT_PAGE },
      { title: "MDN Web Docs - Web Technology Reference", kind: "Reference", url: "https://developer.mozilla.org/en-US/" },
      { title: "freeCodeCamp - Free Web Dev Courses", kind: "Course", url: "https://www.freecodecamp.org/" },
      { title: "web.dev - Modern Web Development (Google)", kind: "Course", url: "https://web.dev/learn/" },
    ],
    isTeam: true,
    rubricUrl: FBLA_EVENT_PAGE,
    contentStatus: "complete",
  },
];

export function getCompetition(slug: string): Competition | undefined {
  return COMPETITIONS.find((c) => c.slug === slug);
}

export function getCompetitionsByCategory(category: CompetitionCategory): Competition[] {
  return COMPETITIONS.filter((c) => c.category === category);
}

export function getPopularCompetitions(): Competition[] {
  return COMPETITIONS.filter((c) => c.popular);
}

export function getAvailableCompetitions(): Competition[] {
  return COMPETITIONS.filter((c) => c.contentStatus !== "coming-soon");
}

/** Quick stats for the marketing site. */
export const COMPETITION_STATS = {
  total: COMPETITIONS.length,
  withContent: COMPETITIONS.filter((c) => c.contentStatus === "complete").length,
  categories: CATEGORIES.length,
};
