/**
 * Lightweight competition index - slug, name, and category only.
 *
 * STANDALONE: this module does NOT import the heavy COMPETITIONS array, so
 * components that only need to list or search events (e.g. the globally-mounted
 * CommandPalette) no longer pull the full registry - longDescription, topics,
 * studyResources - into every page bundle. Keep in sync with lib/competitions.ts;
 * a dev-only guard there warns on drift. Generated in registry order.
 */
export type CompetitionIndexItem = { slug: string; name: string; category: string };

export const COMPETITION_INDEX: CompetitionIndexItem[] = [
  { slug: "accounting-i", name: "Accounting I", category: "Accounting & Finance" },
  { slug: "accounting-ii", name: "Accounting II", category: "Accounting & Finance" },
  { slug: "personal-finance", name: "Personal Finance", category: "Accounting & Finance" },
  { slug: "financial-math", name: "Financial Math", category: "Accounting & Finance" },
  { slug: "intro-to-financial-math", name: "Intro to Financial Math", category: "Accounting & Finance" },
  { slug: "securities-investments", name: "Securities & Investments", category: "Accounting & Finance" },
  { slug: "banking-financial-systems", name: "Banking & Financial Systems", category: "Accounting & Finance" },
  { slug: "insurance-risk-management", name: "Insurance & Risk Management", category: "Accounting & Finance" },
  { slug: "business-management", name: "Business Management", category: "Business Management" },
  { slug: "business-law", name: "Business Law", category: "Business Management" },
  { slug: "business-calculations", name: "Business Calculations", category: "Business Management" },
  { slug: "business-communication", name: "Business Communication", category: "Communication & Public Speaking" },
  { slug: "economics", name: "Economics", category: "Business Management" },
  { slug: "marketing", name: "Marketing", category: "Marketing & Sales" },
  { slug: "advertising", name: "Advertising", category: "Marketing & Sales" },
  { slug: "sports-entertainment-management", name: "Sports & Entertainment Management", category: "Marketing & Sales" },
  { slug: "supply-chain-management", name: "Supply Chain Management", category: "Business Management" },
  { slug: "health-care-administration", name: "Health Care Administration", category: "Business Management" },
  { slug: "agribusiness", name: "Agribusiness", category: "Business Management" },
  { slug: "computer-applications", name: "Computer Applications", category: "Information Technology" },
  { slug: "computer-problem-solving", name: "Computer Problem Solving", category: "Information Technology" },
  { slug: "cyber-security", name: "Cyber Security", category: "Information Technology" },
  { slug: "networking-infrastructures", name: "Networking Infrastructures", category: "Information Technology" },
  { slug: "intro-to-information-technology", name: "Intro to Information Technology", category: "Information Technology" },
  { slug: "management-information-systems", name: "Management Information Systems", category: "Information Technology" },
  { slug: "coding-programming", name: "Coding & Programming", category: "Information Technology" },
  { slug: "word-processing", name: "Word Processing", category: "Information Technology" },
  { slug: "intro-to-fbla", name: "Intro to FBLA", category: "Career Development" },
  { slug: "intro-to-business", name: "Intro to Business", category: "Business Management" },
  { slug: "intro-to-business-communication", name: "Intro to Business Communication", category: "Communication & Public Speaking" },
  { slug: "intro-to-business-procedures", name: "Intro to Business Procedures", category: "Business Management" },
  { slug: "political-science", name: "Political Science", category: "Career Development" },
  { slug: "future-business-leader", name: "Future Business Leader", category: "Career Development" },
  { slug: "future-business-educator", name: "Future Business Educator", category: "Career Development" },
  { slug: "broadcast-journalism", name: "Broadcast Journalism", category: "Communication & Public Speaking" },
  { slug: "business-ethics", name: "Business Ethics", category: "Service & Leadership" },
  { slug: "business-financial-plan", name: "Business Financial Plan", category: "Accounting & Finance" },
  { slug: "business-plan", name: "Business Plan", category: "Marketing & Sales" },
  { slug: "community-service-project", name: "Community Service Project", category: "Service & Leadership" },
  { slug: "data-analysis", name: "Data Analysis", category: "Information Technology" },
  { slug: "digital-animation", name: "Digital Animation", category: "Information Technology" },
  { slug: "digital-video-production", name: "Digital Video Production", category: "Communication & Public Speaking" },
  { slug: "entrepreneurship", name: "Entrepreneurship", category: "Business Management" },
  { slug: "graphic-design", name: "Graphic Design", category: "Marketing & Sales" },
  { slug: "hospitality-event-management", name: "Hospitality & Event Management", category: "Business Management" },
  { slug: "impromptu-speaking", name: "Impromptu Speaking", category: "Communication & Public Speaking" },
  { slug: "introduction-to-public-speaking", name: "Intro to Public Speaking", category: "Communication & Public Speaking" },
  { slug: "job-interview", name: "Job Interview", category: "Career Development" },
  { slug: "mobile-application-development", name: "Mobile Application Development", category: "Information Technology" },
  { slug: "parliamentary-procedure", name: "Parliamentary Procedure", category: "Service & Leadership" },
  { slug: "public-service-announcement", name: "Public Service Announcement", category: "Communication & Public Speaking" },
  { slug: "public-speaking", name: "Public Speaking", category: "Communication & Public Speaking" },
  { slug: "publication-design", name: "Publication Design", category: "Marketing & Sales" },
  { slug: "social-media-strategies", name: "Social Media Strategies", category: "Marketing & Sales" },
  { slug: "website-coding-development", name: "Website Coding & Development", category: "Information Technology" },
];
